// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: Pulse_Generate

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_IO1_Label = NULL;
lv_obj_t * ui_IO2_Label = NULL;
lv_obj_t * ui_IO3_Label = NULL;
lv_obj_t * ui_IO4_Label = NULL;
lv_obj_t * ui_IO1_Switch = NULL;
lv_obj_t * ui_IO2_Switch = NULL;
lv_obj_t * ui_IO3_Switch = NULL;
lv_obj_t * ui_IO4_Switch = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_slider_increment(ui_Slider1, -1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_slider_increment(ui_Slider1, -1, LV_ANIM_ON);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_slider_increment(ui_Slider1, 1, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_slider_increment(ui_Slider1, 1, LV_ANIM_ON);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_slider_increment(ui_Slider2, -10, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_slider_increment(ui_Slider2, -10, LV_ANIM_ON);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_slider_increment(ui_Slider2, 10, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_slider_increment(ui_Slider2, 10, LV_ANIM_ON);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label4, target, "", "");
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label9, target, "", "");
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -135);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Pulse Generate");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Times_New_Roman_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 8);
    lv_obj_set_y(ui_Label2, -90);
    lv_obj_set_align(ui_Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label2, "Pulse Number");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Times_New_Roman_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 25);
    lv_obj_set_height(ui_Button1, 20);
    lv_obj_set_x(ui_Button1, -1);
    lv_obj_set_y(ui_Button1, -90);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button1, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xA5A5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x7395E6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Button1, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Button1, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xEEEBB4), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_Button1, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_Button1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label3 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "-");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, 50);
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 50);
    lv_obj_set_y(ui_Label4, -90);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "2");
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Times_New_Roman_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Label4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Label4, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 25);
    lv_obj_set_height(ui_Button2, 20);
    lv_obj_set_x(ui_Button2, 100);
    lv_obj_set_y(ui_Button2, -90);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xA5A5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x7395E6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Button2, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Button2, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xEEEBB4), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_Button2, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_Button2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label6 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "+");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 8);
    lv_obj_set_y(ui_Label7, -40);
    lv_obj_set_align(ui_Label7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label7, "Pulse Width");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Times_New_Roman_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 25);
    lv_obj_set_height(ui_Button3, 20);
    lv_obj_set_x(ui_Button3, -1);
    lv_obj_set_y(ui_Button3, -40);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xA5A5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x7395E6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xEEEBB4), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_Button3, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_Button3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label8 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "-");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, 50);
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 50);
    lv_obj_set_y(ui_Label9, -40);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "100000");
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Times_New_Roman_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Label9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Label9, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button4, 25);
    lv_obj_set_height(ui_Button4, 20);
    lv_obj_set_x(ui_Button4, 100);
    lv_obj_set_y(ui_Button4, -40);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xA5A5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x7395E6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xEEEBB4), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_Button4, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_Button4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label10 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "+");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, 105);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Sunshine Circuit");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Times_New_Roman_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 60);
    lv_obj_set_y(ui_Switch1, 10);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xEEEBB4), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_outline_color(ui_Switch1, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Switch1, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Switch1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x7396E6), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_Switch1, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_outline_color(ui_Switch1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Switch1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Switch1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x146EE6), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_Switch1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 8);
    lv_obj_set_y(ui_Label12, 10);
    lv_obj_set_align(ui_Label12, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label12, "Generate");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Times_New_Roman_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider1, 2, 102);
    lv_slider_set_value(ui_Slider1, 2, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 90);
    lv_obj_set_height(ui_Slider1, 5);
    lv_obj_set_x(ui_Slider1, -60);
    lv_obj_set_y(ui_Slider1, -70);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Slider2 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider2, 100, 100000);
    lv_slider_set_value(ui_Slider2, 100000, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 100, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 90);
    lv_obj_set_height(ui_Slider2, 5);
    lv_obj_set_x(ui_Slider2, -60);
    lv_obj_set_y(ui_Slider2, -20);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    ui_IO1_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_IO1_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IO1_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IO1_Label, -90);
    lv_obj_set_y(ui_IO1_Label, 45);
    lv_obj_set_align(ui_IO1_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IO1_Label, "IO1");
    lv_obj_set_style_text_font(ui_IO1_Label, &ui_font_Times_New_Roman_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IO2_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_IO2_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IO2_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IO2_Label, -30);
    lv_obj_set_y(ui_IO2_Label, 45);
    lv_obj_set_align(ui_IO2_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IO2_Label, "IO2");
    lv_obj_set_style_text_font(ui_IO2_Label, &ui_font_Times_New_Roman_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IO3_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_IO3_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IO3_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IO3_Label, 30);
    lv_obj_set_y(ui_IO3_Label, 45);
    lv_obj_set_align(ui_IO3_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IO3_Label, "IO3");
    lv_obj_set_style_text_font(ui_IO3_Label, &ui_font_Times_New_Roman_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IO4_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_IO4_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IO4_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IO4_Label, 90);
    lv_obj_set_y(ui_IO4_Label, 45);
    lv_obj_set_align(ui_IO4_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IO4_Label, "IO4");
    lv_obj_set_style_text_font(ui_IO4_Label, &ui_font_Times_New_Roman_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IO1_Switch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_IO1_Switch, 50);
    lv_obj_set_height(ui_IO1_Switch, 25);
    lv_obj_set_x(ui_IO1_Switch, -90);
    lv_obj_set_y(ui_IO1_Switch, 70);
    lv_obj_set_align(ui_IO1_Switch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_IO1_Switch, lv_color_hex(0xEEEBB4), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_IO1_Switch, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_outline_color(ui_IO1_Switch, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IO1_Switch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IO1_Switch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IO1_Switch, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IO1_Switch, lv_color_hex(0x7396E6), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_IO1_Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_IO1_Switch, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_IO1_Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_outline_color(ui_IO1_Switch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IO1_Switch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IO1_Switch, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IO1_Switch, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IO1_Switch, lv_color_hex(0x146EE6), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_IO1_Switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_IO1_Switch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_IO1_Switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_IO2_Switch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_IO2_Switch, 50);
    lv_obj_set_height(ui_IO2_Switch, 25);
    lv_obj_set_x(ui_IO2_Switch, -30);
    lv_obj_set_y(ui_IO2_Switch, 70);
    lv_obj_set_align(ui_IO2_Switch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_IO2_Switch, lv_color_hex(0xEEEBB4), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_IO2_Switch, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_outline_color(ui_IO2_Switch, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IO2_Switch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IO2_Switch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IO2_Switch, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IO2_Switch, lv_color_hex(0x7396E6), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_IO2_Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_IO2_Switch, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_IO2_Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_outline_color(ui_IO2_Switch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IO2_Switch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IO2_Switch, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IO2_Switch, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IO2_Switch, lv_color_hex(0x146EE6), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_IO2_Switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_IO2_Switch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_IO2_Switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_IO3_Switch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_IO3_Switch, 50);
    lv_obj_set_height(ui_IO3_Switch, 25);
    lv_obj_set_x(ui_IO3_Switch, 30);
    lv_obj_set_y(ui_IO3_Switch, 70);
    lv_obj_set_align(ui_IO3_Switch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_IO3_Switch, lv_color_hex(0xEEEBB4), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_IO3_Switch, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_outline_color(ui_IO3_Switch, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IO3_Switch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IO3_Switch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IO3_Switch, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IO3_Switch, lv_color_hex(0x7396E6), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_IO3_Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_IO3_Switch, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_IO3_Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_outline_color(ui_IO3_Switch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IO3_Switch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IO3_Switch, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IO3_Switch, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IO3_Switch, lv_color_hex(0x146EE6), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_IO3_Switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_IO3_Switch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_IO3_Switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_IO4_Switch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_IO4_Switch, 50);
    lv_obj_set_height(ui_IO4_Switch, 25);
    lv_obj_set_x(ui_IO4_Switch, 90);
    lv_obj_set_y(ui_IO4_Switch, 68);
    lv_obj_set_align(ui_IO4_Switch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_IO4_Switch, lv_color_hex(0xEEEBB4), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_IO4_Switch, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_outline_color(ui_IO4_Switch, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IO4_Switch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IO4_Switch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IO4_Switch, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IO4_Switch, lv_color_hex(0x7396E6), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_IO4_Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_IO4_Switch, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_IO4_Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_outline_color(ui_IO4_Switch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IO4_Switch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_IO4_Switch, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_IO4_Switch, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IO4_Switch, lv_color_hex(0x146EE6), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_IO4_Switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_outline_color(ui_IO4_Switch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_outline_opa(ui_IO4_Switch, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Button1 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Button2 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Button3 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Button4 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Switch1 = NULL;
    ui_Label12 = NULL;
    ui_Slider1 = NULL;
    ui_Slider2 = NULL;
    ui_IO1_Label = NULL;
    ui_IO2_Label = NULL;
    ui_IO3_Label = NULL;
    ui_IO4_Label = NULL;
    ui_IO1_Switch = NULL;
    ui_IO2_Switch = NULL;
    ui_IO3_Switch = NULL;
    ui_IO4_Switch = NULL;

}
